export const citiesData = [
    { name: 'New York', country: 'US', value: 'New York, US' },
    { name: 'Los Angeles', country: 'US', value: 'Los Angeles, US' },
    { name: 'Chicago', country: 'US', value: 'Chicago, US' },
    { name: 'San Jose', country: 'US', value: 'San Jose, US' },
    { name: 'Austin', country: 'US', value: 'Austin, US' },
    { name: 'San Francisco', country: 'US', value: 'San Francisco, US' },
    { name: 'Seattle', country: 'US', value: 'Seattle, US' },
    { name: 'Denver', country: 'US', value: 'Denver, US' },
    { name: 'Boston', country: 'US', value: 'Boston, US' },
    { name: 'San Diego', country: 'US', value: 'San Diego, US' },
    { name: "London", country: 'UK', value: 'London, UK' },
    { name: "Manchester", country: 'UK', value: 'Manchester, UK' },
    { name: 'Cambridge', country: 'UK', value: 'Cambridge, UK' },
    { name: 'Toronto', country: 'CA', value: 'Toronto, CA' },
    { name: 'Vancouver', country: 'CA', value: 'Vancouver, CA' },
    { name: 'Montreal', country: 'CA', value: 'Montreal, CA' },
    { name: 'Paris', country: 'FR', value: 'Paris, FR' },
    { name: 'Lyon', country: 'FR', value: 'Lyon, FR' },
    { name: 'Toulouse', country: 'FR', value: 'Toulouse, FR' },
    { name: 'Berlin', country: 'DE', value: 'Berlin, DE' },
    { name: 'Munich', country: 'DE', value: 'Munich, DE' },
    { name: 'Hamburg', country: 'DE', value: 'Hamburg, DE' },
    { name: 'Many more cities from 05/21', country: 'Many more cities from 05/21', value: 'Many more cities from 05/21' },
]