export const citiesData = [
    { name: 'New York', country: 'US' },
    { name: 'Los Angeles', country: 'US' },
    { name: 'Chicago', country: 'US' },
    { name: 'Houston', country: 'US' },
    { name: 'Phoenix', country: 'US' },
    { name: 'Philadelphia', country: 'US' },
    { name: 'San Antonio', country: 'US' },
    { name: 'San Diego', country: 'US' },
    { name: 'Dallas', country: 'US' },
    { name: 'San Jose', country: 'US' },
    { name: 'Austin', country: 'US' },
    { name: 'Jacksonville', country: 'US' },
    { name: 'Fort Worth', country: 'US' },
    { name: 'Columbus', country: 'US' },
    { name: 'San Francisco', country: 'US' },
    { name: 'Charlotte', country: 'US' },
    { name: 'Indianapolis', country: 'US' },
    { name: 'Seattle', country: 'US' },
    { name: 'Denver', country: 'US' },
    { name: 'Washington', country: 'US' },
    { name: 'Boston', country: 'US' },
    { name: 'El Paso', country: 'US' },
    { name: 'Nashville', country: 'US' },
    { name: 'Detroit', country: 'US' },
    { name: 'Oklahoma City', country: 'US' },
    { name: 'Portland', country: 'US' },
    { name: 'Las Vegas', country: 'US' },
    { name: 'Memphis', country: 'US' },
    { name: 'Louisville', country: 'US' },
    { name: 'Baltimore', country: 'US' },
    { name: 'Milwaukee', country: 'US' },
    { name: 'Albuquerque', country: 'US' },
    { name: 'Tucson', country: 'US' },
    { name: 'Fresno', country: 'US' },
    { name: 'Mesa', country: 'US' },
    { name: 'Sacramento', country: 'US' },
    { name: 'Atlanta', country: 'US' },
    { name: 'Kansas City', country: 'US' }
]