export const citiesData = [
    {name: "New York"},
    {name: "Los Angeles"},
    {name: "Chicago"},
    {name: "Houston"},
    {name: "Phoenix"},
    {name: "Philadelphia"},
    {name: "San Antonio"},
    {name: "San Diego"},
    {name: "Dallas"},
    {name: "San Jose"},
    {name: "Austin"},
    {name: "Jacksonville"},
    {name: "Fort Worth"},
    {name: "Columbus"},
    {name: "San Francisco"},
    {name: "Charlotte"},
    {name: "Indianapolis"},
    {name: "Seattle"},
    {name: "Denver"},
    {name: "Washington"},
    {name: "Boston"},
    {name: "El Paso"},
    {name: "Nashville"},
    {name: "Detroit"},
]