interface Industry {
    name: string;
}
//remplacer par vrai industrie de Crunchbase
export const industries: Industry[] = [
    { name: "Technology" },
    { name: "Healthcare" },
    { name: "Manufacturing" },
    { name: "Education" },
    { name: "Real Estate" },
    { name: "Retail" },
    { name: "Transportation" },
    { name: "Construction" },
    { name: "Energy" },
    { name: "Agriculture" },
    { name: "Hospitality" },
    { name: "Entertainment" },
    { name: "Food & Beverages" },
    { name: "Professional Services" },
    { name: "Information Technology" },
    { name: "Telecommunications" },
    { name: "Automotive" },
    { name: "Aerospace" },
    { name: "Pharmaceuticals" },
    { name: "Non-Profit Organization" },
    { name: "Government" },
    { name: "Biotechnology" },
    { name: "Mining" },
    { name: "Utilities" },
    { name: "Chemicals" },
    { name: "Consumer Goods" },
    { name: "Defense & Space" },
    { name: "Maritime" },
    { name: "Paper & Forest Products" },
    { name: "Railroad Manufacture" },
    { name: "Ranching" },
    { name: "Luxury Goods & Jewelry" },
    { name: "Renewable & Environment" },
    { name: "Sporting Goods" },
    { name: "Textiles" },
    { name: "Logistics & Supply Chain" },
    { name: "Public Relations & Communications" },
    { name: "Law Practice" },
    { name: "Political Organization" },
    { name: "Civic & Social Organization" },
    { name: "E-Learning" },
    { name: "Wholesale" },
    { name: "Import & Export" },
    { name: "Mechanical or Industrial Engineering" },
    { name: "Nanotechnology" },
    { name: "Graphic Design" },
    { name: "Online Media" },
    { name: "Publishing" },
    { name: "Think Tanks" },
    { name: "Marketing & Advertising" },
    { name: "Digital Marketing" },
    { name: "Copywriting" },
    { name: "SEO & SEM Services" },
    { name: "Public Relations" },
    { name: "Branding" },
    { name: "Market Research" },
    { name: "Marketing Consulting" },
    { name: "Social Media Marketing" },
    { name: "Content Marketing" },
    { name: "Email Marketing" },
    { name: "Video Production" },
    { name: "Advertising Technology" },
    { name: "Marketing Automation" },
    { name: "Web Design & Development" },
    { name: "Software Development" },
    { name: "Web Development" },
    { name: "Mobile App Development" },
    { name: "Application Security" },
    { name: "Cloud Computing Services" },
    { name: "Data Analytics & Big Data" },
    { name: "Artificial Intelligence & Machine Learning" },
    { name: "Internet of Things (IoT)" },
    { name: "Augmented Reality & Virtual Reality" },
    { name: "User Experience (UX) & User Interface (UI) Design" },
    { name: "E-commerce Solutions" },
    { name: "CRM & ERP Solutions" },
    { name: "API Development" },
    { name: "DevOps & Infrastructure" },
    { name: "Database Management & Development" },
    { name: "Software Testing & QA" },
    { name: "Cybersecurity Services" },
    { name: "IT Consulting" },
    { name: "Technical Support & Maintenance" },
    { name: "Networking & Information Systems" },
    { name: "Open Source Development" },
    { name: "Content Management System (CMS) Development" },
    { name: "Software as a Service (SaaS)" },
    { name: "Platform as a Service (PaaS)" },
    { name: "Infrastructure as a Service (IaaS)" },
    { name: "Fintech" },
    { name: "EdTech" },
    { name: "HealthTech" },
    { name: "LegalTech" },
    { name: "AgriTech" },
    { name: "CleanTech" },
    { name: "GovTech" },
  ];
  